name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: golang:latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - name: go version
        run: go version

      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Setup Cache
        uses: actions/cache@v2.1.7
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build and Test
        run: |
          make build test
